# Generated by Django 3.0.4 on 2021-03-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='projectstats',
            options={'verbose_name': 'Project Stat', 'verbose_name_plural': 'Project Stats'},
        ),
    ]
