# Generated by Django 3.0.4 on 2021-03-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210304_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.CharField(max_length=50, null=True, verbose_name='Task'),
        ),
    ]
