# Generated by Django 3.0.4 on 2021-03-10 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210304_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 12, 11, 49, 720056, tzinfo=utc), verbose_name='published date'),
        ),
    ]
